WebApp/Controllers/BackController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Domain;
using Newtonsoft.Json;

namespace WebApp.Controllers
{
    public class BackController : Controller
    {
        Admin system = Admin.Instance;
        // GET: Back
        public ActionResult TryLogin(string username, string password)
        {
            foreach(User u in system.Users)
            {
                if(u.Username == username && u.Password == password)
                {
                    system.Login(u);
                    return RedirectToAction("Index", "Main");
                }
            }
            ViewBag.logerror = true;
            return View("~/Views/Main/Login.cshtml");
        }

        public ActionResult Register(string username, string password)
        {
            system.AddUser(username, password);
            return RedirectToAction("Login", "Main");
        }

        public ActionResult Logout()
        {
            system.Logout();
            return RedirectToAction("Index", "Main");
        }

        [HttpPost]

        public ActionResult UpvoteQ(string data)
        {
            string[] words = data.Split(' ');
            string qId = words[0];
            int userId = int.Parse(words[1]);
            system.UpvoteQuestion(qId, userId);
            return PartialView("_Partial");
        }

        public ActionResult RemoveUpvoteQ(string data)
        {
            string[] words = data.Split(' ');
            string qId = words[0];
            int userId = int.Parse(words[1]);
            system.RemoveUpvoteQ(qId, userId);
            return PartialView("_Partial");
        }

        public ActionResult UpvoteA(string data)
        {
            string[] words = data.Split(' ');
            string qId = words[1];
            string aId = words[0];
            int userId = int.Parse(words[2]);
            system.UpvoteAnswer(qId, aId, userId);
            return PartialView("_Partial");
        }
        
        public ActionResult RemoveUpvoteA(string data)
        {
            string[] words = data.Split(' ');
            string qId = words[1];
            string aId = words[0];
            int userId = int.Parse(words[2]);
            system.RemoveUpvoteA(qId, aId, userId);
            return PartialView("_Partial");
        }


    }
}

WebApp/Controllers/MainController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Domain;


namespace WebApp.Controllers
{
    public class MainController : Controller
    {
        Admin system = Admin.Instance;

        // GET: Main
        public ActionResult Index()
        {
            ViewBag.loggedIn = system.LoggedUser;
            ViewBag.questions = system.Questions;
            ViewBag.users = system.Users;
            return View();
        }

        public ActionResult Login()
        {
            ViewBag.logerror = false;
            return View();
        }

        public ActionResult Register()
        {
            ViewBag.users = system.Users;
            return View();
        }
    }
}

WebApp/Views/Main/Index.cshtml
@{
    ViewBag.Title = "Index";
}
@using Domain;

<div class="container">
    <main class="container-articles">
        @foreach (Question q in ViewBag.questions)
        {
            <article class="post">
                <h2 class="question">@q.Content</h2>
                <div class="flex">
                    @foreach (User u in ViewBag.users)
                    {
                        if (u.Id == q.UserId)
                        {
                            if (u.Username != ViewBag.loggedIn.Username)
                            {
                                <p class="q-user">
                                    by
                                    @u.Username
                                </p>
                            }
                            else
                            {
                                <p class="q-user">
                                    by
                                    Me
                                </p>
                            }
                        }
                    }
                    @if (ViewBag.loggedIn.Username == "null")
                    {
                        <txt>&nbsp&nbsp</txt>
                        <a class="upvote" href="/Main/Login">
                            <svg width="10" height="8" viewBox="0 0 10 8" fill="none" xmlns="http://www.w3.org/2000/svg">
                                <path d="M5 8L0.669873 0.499999L9.33013 0.5L5 8Z" fill="black" />
                            </svg>
                        </a>
                    }
                    else
                    {
                        if (q.Upvotes.Count == 0)
                        {
                            <button id="@q.Id" class="upvote" onclick="upVoteQ(@q.Id)">
                                <svg width="10" height="8" viewBox="0 0 10 8" fill="none" xmlns="http://www.w3.org/2000/svg">
                                    <path d="M5 8L0.669873 0.499999L9.33013 0.5L5 8Z" fill="black" />
                                </svg>
                            </button>
                        }
                        else
                        {
                            bool liked = false;
                            foreach (Upvote u in q.Upvotes)
                            {
                                if (u.UserId == ViewBag.loggedIn.Id)
                                {
                                    liked = true;
                                }
                            }

                            if (liked)
                            {
                                <button id="@q.Id" class="upvote rotate" onclick="upVoteQ(@q.Id)">
                                    <svg width="10" height="8" viewBox="0 0 10 8" fill="none" xmlns="http://www.w3.org/2000/svg">
                                        <path d="M5 8L0.669873 0.499999L9.33013 0.5L5 8Z" fill="black" />
                                    </svg>
                                </button>
                            }
                            else
                            {
                                <button id="@q.Id" class="upvote" onclick="upVoteQ(@q.Id)">
                                    <svg width="10" height="8" viewBox="0 0 10 8" fill="none" xmlns="http://www.w3.org/2000/svg">
                                        <path d="M5 8L0.669873 0.499999L9.33013 0.5L5 8Z" fill="black" />
                                    </svg>
                                </button>
                            }
                        }
                    }
                </div>
                <div class="pseudo-ul">
                    @foreach (Answer a in q.Answers)
                    {
                        <div class="whole-answer">
                            <div class="answer">@a.Content</div>
                            @foreach (User u in ViewBag.users)
                            {
                                if (a.UserId == u.Id)
                                {
                                    <p class="q-user">
                                        @if (u.Username != ViewBag.loggedIn.Username)
                                        {
                                            <txt>by</txt>
                                            @u.Username
                                        }
                                        else
                                        {
                                            <txt>by Me</txt>
                                        }

                                        @if (ViewBag.loggedIn.Username == "null")
                                        {
                                            <txt>&nbsp&nbsp</txt>
                                            <a class="upvote" href="/Main/Login">
                                                <svg width="7" height="5" viewBox="0 0 10 8" fill="none" xmlns="http://www.w3.org/2000/svg">
                                                    <path d="M5 8L0.669873 0.499999L9.33013 0.5L5 8Z" fill="black" />
                                                </svg>
                                            </a>
                                        }
                                        else
                                        {
                                            if (a.Upvotes.Count == 0)
                                            {
                                                <button id="@a.Id" class="upvote" onclick="upVoteA(@a.Id, @q.Id)">
                                                    <svg width="7" height="5" viewBox="0 0 10 8" fill="none" xmlns="http://www.w3.org/2000/svg">
                                                        <path d="M5 8L0.669873 0.499999L9.33013 0.5L5 8Z" fill="black" />
                                                    </svg>
                                                </button>
                                            }
                                            else
                                            {
                                                bool liked = false;
                                                foreach (Upvote up in a.Upvotes)
                                                {
                                                    if (up.UserId == ViewBag.loggedIn.Id)
                                                    {
                                                        liked = true;
                                                    }
                                                }

                                                if (liked)
                                                {
                                                    <button id="@a.Id" class="upvote rotate-a" onclick="upVoteA(@a.Id, @q.Id)">
                                                        <svg width="7" height="5" viewBox="0 0 10 8" fill="none" xmlns="http://www.w3.org/2000/svg">
                                                            <path d="M5 8L0.669873 0.499999L9.33013 0.5L5 8Z" fill="black" />
                                                        </svg>
                                                    </button>
                                                }
                                                else
                                                {
                                                    <button id="@a.Id" class="upvote" onclick="upVoteA(@a.Id, @q.Id)">
                                                        <svg width="7" height="5" viewBox="0 0 10 8" fill="none" xmlns="http://www.w3.org/2000/svg">
                                                            <path d="M5 8L0.669873 0.499999L9.33013 0.5L5 8Z" fill="black" />
                                                        </svg>
                                                    </button>
                                                }
                                            }

                                        }
                                    </p>
                                }
                            }
                        </div>
                    }
                </div>
            </article>
        }
    </main>

</div>

<script>

    function upVoteQ(id) {
        id.classList.toggle("rotate");

        let send = id.id + " @ViewBag.loggedIn.Id";

        if (id.classList.contains("rotate")) {
            $.ajax({
                type: "POST",
                dataType: "application/json; charset=utf-8",
                data: { "data": send },
                url: "@Url.Action("UpvoteQ", "Back")",
            });
        } else {
            $.ajax({
                type: "POST",
                dataType: "application/json; charset=utf-8",
                data: { "data": send },
                url: "@Url.Action("RemoveUpvoteQ", "Back")",
            });
        }
        return;
    }

    function upVoteA(a, q) {
        a.classList.toggle("rotate-a");

        let send = a.id + " " + q.id + " @ViewBag.loggedIn.Id";

        if (a.classList.contains("rotate-a")) {
            $.ajax({
                type: "POST",
                dataType: "application/json; charset=utf-8",
                data: { "data": send },
                url: "@Url.Action("UpvoteA", "Back")",
            });
        } else {
            $.ajax({
                type: "POST",
                dataType: "application/json; charset=utf-8",
                data: { "data": send },
                url: "@Url.Action("RemoveUpvoteA", "Back")",
            });
        }
        return;
    }

</script>

@Html.Partial("_Partial")

WebApp/Views/Main/Login.cshtml
@{
    ViewBag.Title = "Login";
}

<section>
    <div class="form_div">
        <div class="login-title">
            <h1>Login</h1>
        </div>
        <form action="/Back/TryLogin" method="post">
            <div class="form_input">
                <label for="username">Username</label>
                <input required type="text" autocomplete="on" id="username" name="username" />
            </div>

            <div class="form_input">
                <label for="password">Password</label>
                <input required type="password" autocomplete="off" id="password" name="password" />
            </div>

            <button class="form-button first" type="submit">Login</button>
        </form>
            <button class="form-button">
                @Html.ActionLink("Register", "Register", "Main", null, new { @style = "color: white; padding-left: 33%; padding-right: 33%; padding-top: 10px; padding-bottom: 10px;" })
            </button>
    </div>
</section>

@if (ViewBag.logerror)
{
@Html.Partial("_LoginFailed")
}

WebApp/Views/Main/Register.cshtml
@{
    ViewBag.Title = "Register";
}

<section class="s-flex">
    <div class="form_div">
        <div class="login-title">
            <h1>Register</h1>
        </div>
        <form action="/Back/Register" method="post" onsubmit="return TryReg()">
            <div class="form_input">
                <label for="username">Username</label>
                <input required type="text" autocomplete="off" id="username" name="username" />
            </div>

            <div class="form_input">
                <label for="password">Password</label>
                <input required type="password" autocomplete="off" id="password" name="password" />
            </div>

            <div class="form_input">
                <label for="c_password">Re-enter Password</label>
                <input required type="password" autocomplete="off" id="c_password" name="c_password" />
            </div>

            <button class="form-button first" type="submit">Submit</button>
        </form>
    </div>
    <div class="error_dialog">
        <h2 class="main_error">Something went wrong!</h2>
        <p>
            Remember: <br>
            - Username needs 5 or more characters <br />
            - Password has to be at least 6 characters long <br />
            - Password should have 1 uppercase, 1 lowercase and 1 number
        </p>
    </div>
</section>


<script src="~/Scripts/jquery-1.10.2.min.js"></script>

<script>

    $(document).ready(() => {
        $(".error_dialog").hide();
    });

    function TryReg() {
        $(".error_dialog").hide();
        $(".main_error").html("Something went wrong!");

        let username = $("#username").val().toLowerCase();
        let password = $("#password").val();
        let c_password = $("#c_password").val();
        let users = @Html.Raw(Json.Encode(ViewBag.users));

        usernameOk = false;
        passwordOk = false;

        //Username Verification
        if (username.length < 5) {
            $(".main_error").html("This username too short!");
            $(".error_dialog").show("fast");
            return false;
        } else {
            for (i = 0; i < users.length; i++) {
                if (username == users[i].Username.toLowerCase()) {
                    $(".main_error").html("This username is already in use");
                    $(".error_dialog").show("fast");
                    return false;
                }
            }
            usernameOk = true;
        }

        //Password Verification
        if (password.length < 6) {
            $(".main_error").html("Password too short!");
            return false;
        } else {
            let upper = false;
            let lower = false;
            let number = false;

            for (i = 0; i < password.length; i++) {
                let char = password.charCodeAt(i);
                if (char > 96 && char < 123) {
                    lower = true;
                } else if (char > 64 && char < 91) {
                    upper = true;
                } else if (char > 48 && char < 58) {
                    number = true;
                }
            }

            if (!upper || !lower || !number) {
                $(".main_error").html("This password is not valid");
                $(".error_dialog").show("fast");
                return false;
            } else if (password != c_password) {
                $(".main_error").html("Passwords don't match");
                $(".error_dialog").show("fast");
            } else {
                passwordOk = true;
            }
        }

        if (passwordOk && usernameOk) {
            $(".error_dialog").hide("fast");
            return true;
        }
        return false;
    }

</script>

WebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - AsQ&A</title>
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Lato:wght@300&display=swap" rel="stylesheet">
    <link rel="shortcut icon" type="image/x-icon" href="~/img/favicon.svg">
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
    <link href="~/Content/style.css" rel="stylesheet" type="text/css" />
</head>
<body>
    <div class="container">
        <nav>
            <a class="a-img" href="/Main/Index">
                <svg width="301" height="221" viewBox="0 0 301 221" fill="none" xmlns="http://www.w3.org/2000/svg">
                    <path d="M3.72545 180.317C3.56711 180.642 1.64263 184.127 2.05878 184.873C2.42103 185.523 3.43174 185.686 4.16989 185.595C11.6783 184.669 16.7957 179.828 21.9477 174.206C46.9737 146.896 61.9809 110.741 78.0588 77.9841C84.2226 65.4262 90.1754 52.7655 96.3366 40.2063C100.768 31.1725 105.13 22.0999 109.837 13.2063C111.671 9.73956 112.91 5.63173 115.948 3.15074C117.147 2.17148 116.693 6.22542 116.503 7.76185C115.557 15.4091 113.832 22.94 112.559 30.5396C105.119 74.9352 96.3442 121.313 101.503 166.54C103.526 184.271 110.392 218.337 134.948 218.484C142.004 218.526 142.229 215.226 145.725 211.317" stroke="black" stroke-width="4" stroke-linecap="round" stroke-linejoin="round" />
                    <path d="M36.7254 150.317C65.3921 144.984 94.0588 139.651 122.725 134.317" stroke="black" stroke-width="4" stroke-linecap="round" stroke-linejoin="round" />
                    <path d="M140.725 162.317C137.912 156.288 129.544 154.168 123.281 155.873C120.093 156.741 117.504 159.386 119.614 162.873C123.672 169.579 134.384 171.461 141.17 172.929C147.339 174.262 161.141 176.281 149.114 184.262C143.63 187.901 139.032 188.777 132.503 188.151C125.354 187.465 123.912 184.509 118.725 181.317" stroke="black" stroke-width="4" stroke-linecap="round" stroke-linejoin="round" />
                    <path d="M125.203 99.5214C120.172 72.0631 122.511 41.4048 145.48 22.2436C155.211 14.1261 168.588 7.81657 181.647 9.18808C199.899 11.105 212.93 26.1685 218.203 42.7436C227.832 73.0159 214.951 109.208 184.48 121.799C171.612 127.117 157.58 127.263 145.091 120.744C133.399 114.641 130.013 105.086 124.203 94.5214" stroke="#D7385E" stroke-width="6" stroke-linecap="round" stroke-linejoin="round" />
                    <path d="M171.203 108.521C185.05 124.046 198.627 139.764 212.203 155.521" stroke="#D7385E" stroke-width="6" stroke-linecap="round" stroke-linejoin="round" />
                    <path d="M229.701 123.606C230.315 131.52 230.763 142.697 219.201 140.328C202.737 136.956 218.94 121.235 224.145 115.717C234.895 104.321 215.739 102.313 214.145 108.273C210.846 120.615 223.828 136.647 229.701 146.606" stroke="black" stroke-linecap="round" stroke-linejoin="round" />
                    <path d="M192 185.313C201.875 194.269 212.297 180.907 218 173.091C242.039 140.143 254.734 100.967 274.778 65.8686C275.28 64.9888 277.449 63.3017 277.389 64.313C277.019 70.5669 274.93 76.5994 273.778 82.7575C269.411 106.096 264.726 127.201 264.444 151.091C264.32 161.681 264.734 174.293 272.111 182.98C276.675 188.354 274.865 183.185 278 184.313" stroke="#D7385E" stroke-width="4" stroke-linecap="round" stroke-linejoin="round" />
                    <path d="M230 153.313C253 151.313 276 149.313 299 147.313" stroke="#D7385E" stroke-width="4" stroke-linecap="round" stroke-linejoin="round" />
                </svg>
            </a>
            @if (ViewBag.Title != "Login" && ViewBag.Title != "Register")
            {
                <ul>
                    <a href="/Main/Index">
                        <li>Home</li>
                    </a>
                    @if (ViewBag.loggedIn.Username == "null")
                    {
                        <a href="/Main/Login">
                            <li>Profile</li>
                        </a>
                    }
                    else
                    {
                        <a href="#">
                            <li>@ViewBag.loggedIn.Username</li>
                        </a>
                    }

                    @if (ViewBag.loggedIn.Username == "null")
                    {
                        <li><a class="btn custom-btn" href="/Main/Login">Login</a></li>
                    }
                    else
                    {
                        <li><a class="btn custom-btn" href="/Back/Logout">Logout</a></li>
                    }
                </ul>
            }
        </nav>
            </div>

            <div class="container body-content">
                @RenderBody()
            </div>

            <div class="container">
                <hr />
                <footer class="modal-footer">
                    <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
                </footer>
            </div>
            <script src="~/Scripts/jquery-1.10.2.min.js"></script>
            <script src="~/Scripts/bootstrap.min.js"></script>
        </body>
</html>

WebApp/Views/Shared/_LoginFailed.cshtml
<div class="div-error">
    <p class="login-error">
    Incorrect username or password, please try again
    </p>
</div>